# Build configuration for Riverpod code generation
targets:
  $default:
    builders:
      riverpod_generator:
        options:
          # Generate Riverpod providers with proper imports
          enabled: true
